set fileencoding=utf-8
set encoding=utf-8
set fileformat=unix
set backspace=2
set noexpandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set copyindent
set preserveindent
set autoindent
set number
set noruler
set statusline=%-8(%l:%v%)%t
set laststatus=2
set mouse=a
set mousefocus
colorscheme chlordane2
set colorcolumn=81
set syntax=on
let g:powerline_loaded=1
